library(ggplot2)
data("USArrests")
summary_stats <- summary(USArrests)
largest_rape_state <- rownames(USArrests)[which.max(USArrests$Rape)]
max_murder <- max(USArrests$Murder)
min_murder <- min(USArrests$Murder)
correlation_matrix <- cor(USArrests)
median_assault <- median(USArrests$Assault)
bottom_25_murder <- quantile(USArrests$Murder, 0.25)
filtered_states <- rownames(USArrests[USArrests$Assault > median_assault & USArrests$Murder < bottom_25_murder, ])
par(mfrow=c(2,2))
hist(USArrests$Rape, main="Histogram of Rape Arrests", xlab="Rape Arrests")
plot(density(USArrests$Murder), main="Density of Murder Rates", xlab="Murder Rates")
plot(USArrests$Assault, USArrests$Rape, main="Scatterplot of Assault vs Rape", xlab="Assault", ylab="Rape")
barplot(USArrests$Murder, names.arg=rownames(USArrests), main="Bar Graph of Murder Rates", las=2)