library(reshape2)
library(dplyr)
data("ChickWeight")
sorted_data <- ChickWeight %>% arrange(Diet, Time)
melted_data <- melt(ChickWeight, id.vars = c("Chick", "Diet", "Time"))
casted_data <- dcast(melted_data, Diet + variable ~ Time, value.var = "value")
head(sorted_data)
head(melted_data)
head(casted_data)